API: 
  tokenKey: ${BOOKSTORE_TOKEN_KEY}
  tokenExpireSecond: 86400
  

googleOauth2:
  googleVerifyID: 118619557524-ej7k7ceopnn8glgi9foksta3t72vnca3.apps.googleusercontent.com
  googlePassword: ${BOOKSTORE_API_GOOGLEOAUTH2_PASSWORD}
  websiteEmail: wielh.erlow@gmail.com

elastic:
  localIP: "127.0.0.1"
  dockerIP: elastic-container
  dockerComposeIP : elastic-service
  port: 9200
rabbitMQ:
  username: root
  password: ${BOOKSTORE_RABBITMQ_PASSWORD}
  url:
    localIP: "127.0.0.1"
    dockerIP: rabbitMQ-container-0
    dockerComposeIP : rabbitMQ-service-0
    port: 5672
  channelName:
    getVerificationCode: getVerificationCode
mongo:
  username: bookstore_user
  password: ${BOOKSTORE_MONGO_PASSWORD}
  url:
    localIP: "127.0.0.1"
    dockerIP: host.docker.abc
    dockerComposeIP : host.docker.abc
    port: 27017

gate:
  localIP: "127.0.0.1"
  port: 3000 
micro-account:
  localIP: "127.0.0.1"
  dockerIP: micro-account-container
  dockerComposeIP : micro-account-service
  port: 9501
micro-book: 
  localIP: "127.0.0.1"
  dockerIP: micro-book-container
  dockerComposeIP : micro-book-service
  port: 9502
micro-transection: 
  localIP: "127.0.0.1"
  dockerIP: micro-transection-container
  dockerComposeIP : micro-transection-service
  port: 9503
micro-mail:
  url:
    localIP: "127.0.0.1"
    dockerIP: micro-mail-container
    dockerComposeIP : micro-mail-service
    port: 9504
  sendMailport: 465





  

